### ISSUE TITLE
Cleanup and some tweaks

### ISSUE THREAD

**Issue by Outerbeast** [wootguy/hl_c11_a3_anti_troll#1]
Just some stuff that I think should be updated:-
- #L52: te_beampoints paramater `Color c=GREEN` can be changed to `RGBA c= RGBA_GREEN`
Color class and presets can be removed entirely
- That said, `te_beampoints` which requires the doesn't appear to be used at all, might as well remove that too
- Option to let end-user to set whatever `ent` target or targetname to remove instead of the current hardcoded `"leveldead_mm"` value used
- `mineThink` held in a global CScheduledFunction handle, so it can be disabled later in a trigger_script via `RemoveTimer`

```
void disableRespawn(CBaseEntity@ pActivator, CBaseEntity@ pCaller, USE_TYPE useType, float flValue)
{
    if( fnMineThink !is null )
    {
        g_Scheduler.RemoveTimer( fnMineThink );
        @fnMineThink = null;
    }

	respawnMode = false;
}

**Comment by Outerbeast** [comment]
One possible thing that could be done to save having to add the stock HLSP.as code into the same script is handle everything thats currently being done in `MapStart` instead in a global scheduled function
Then hopefully the end user just has to add `map_script hl_c11_a3_anti_troll` and keep `map_script HLSP`
I might make a pull request with these modifications sometime :>

**Comment by Outerbeast** [comment]
> I might make a pull request with these modifications sometime :>

Pull request made
https://github.com/wootguy/hl_c11_a3_anti_troll/pull/2

**Comment by wootguy** [comment]
Merged 👍

**Comment by Outerbeast** [comment]
Have to update the release package :]

**Comment by Outerbeast** [comment]
Don't forget to update the release package :]
